with-expecter: True
dir: mocks/{{ replaceAll .InterfaceDirRelative "internal" "internal_" }} 
mockname: "Mock{{.InterfaceName}}"
outpkg: "mock_{{.PackageName}}"
filename: "mock_{{.InterfaceName}}.go"
all: True
packages:
  github.com/brunobrolesi/marmota-de-briga/internal/business/gateway:
    config:
      recursive: True