version: '3.5'

services:
  api01: &api
    build: 
      context: .
    hostname: api01
    depends_on:
      - scylla-db
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "12MB"

  api02:
    <<: *api 
    hostname: api02
 
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "16MB"

  scylla-db:
    image: scylladb/scylla
    container_name: scylla-db
    hostname: scylla-db
    networks:
      - backend
    command: --developer-mode 1 --skip-wait-for-gossip-to-settle 0
    tty: true
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "510MB"

networks:
  backend:
    driver: bridge