// Code generated by mockery v2.40.3. DO NOT EDIT.

package mock_usecase

import (
	context "context"

	model "github.com/brunobrolesi/marmota-de-briga/internal/business/model"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/brunobrolesi/marmota-de-briga/internal/business/usecase"
)

// MockGetBankStatementUseCase is an autogenerated mock type for the GetBankStatementUseCase type
type MockGetBankStatementUseCase struct {
	mock.Mock
}

type MockGetBankStatementUseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGetBankStatementUseCase) EXPECT() *MockGetBankStatementUseCase_Expecter {
	return &MockGetBankStatementUseCase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, input
func (_m *MockGetBankStatementUseCase) Execute(ctx context.Context, input *usecase.InputGetBankStatement) (*model.BankStatement, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *model.BankStatement
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.InputGetBankStatement) (*model.BankStatement, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *usecase.InputGetBankStatement) *model.BankStatement); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.BankStatement)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *usecase.InputGetBankStatement) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGetBankStatementUseCase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockGetBankStatementUseCase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input *usecase.InputGetBankStatement
func (_e *MockGetBankStatementUseCase_Expecter) Execute(ctx interface{}, input interface{}) *MockGetBankStatementUseCase_Execute_Call {
	return &MockGetBankStatementUseCase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockGetBankStatementUseCase_Execute_Call) Run(run func(ctx context.Context, input *usecase.InputGetBankStatement)) *MockGetBankStatementUseCase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*usecase.InputGetBankStatement))
	})
	return _c
}

func (_c *MockGetBankStatementUseCase_Execute_Call) Return(_a0 *model.BankStatement, _a1 error) *MockGetBankStatementUseCase_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGetBankStatementUseCase_Execute_Call) RunAndReturn(run func(context.Context, *usecase.InputGetBankStatement) (*model.BankStatement, error)) *MockGetBankStatementUseCase_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGetBankStatementUseCase creates a new instance of MockGetBankStatementUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGetBankStatementUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGetBankStatementUseCase {
	mock := &MockGetBankStatementUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
