// Code generated by "gocqlx/cmd/schemagen"; DO NOT EDIT.

package models

import (
	"github.com/scylladb/gocqlx/v2/table"
	"time"
)

// Table models.
var (
	Clients = table.New(table.Metadata{
		Name: "clients",
		Columns: []string{
			"account_balance",
			"account_limit",
			"id",
		},
		PartKey: []string{
			"id",
		},
		SortKey: []string{},
	})

	GocqlxMigrate = table.New(table.Metadata{
		Name: "gocqlx_migrate",
		Columns: []string{
			"checksum",
			"done",
			"end_time",
			"name",
			"start_time",
		},
		PartKey: []string{
			"name",
		},
		SortKey: []string{},
	})

	Transactions = table.New(table.Metadata{
		Name: "transactions",
		Columns: []string{
			"client_id",
			"created_at",
			"description",
			"id",
			"type",
			"value",
		},
		PartKey: []string{
			"client_id",
		},
		SortKey: []string{
			"created_at",
		},
	})
)

type ClientsStruct struct {
	AccountBalance int32
	AccountLimit   int32
	Id             int32
}
type GocqlxMigrateStruct struct {
	Checksum  string
	Done      int32
	EndTime   time.Time
	Name      string
	StartTime time.Time
}
type TransactionsStruct struct {
	ClientId    int32
	CreatedAt   time.Time
	Description string
	Id          [16]byte
	Type        string
	Value       int32
}
